In [1]:
%%writefile sample1.csv
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample1.csv

In [3]:
# CSV는 Comma-Separated Values의 약자로, 데이터를 쉼표(,)로 구분한 텍스트 파일
import csv

csv_file = open("sample1.csv")
reader = csv.reader(csv_file)

for row in reader:
    print(row)
    print(type(row))

['c1', ' c2', ' c3']
<class 'list'>
['1', ' 1.11', ' one']
<class 'list'>
['2', ' 2.22', ' two']
<class 'list'>
['3', ' 3.33', ' three']
<class 'list'>

In [5]:
# CSV 저장
data = [
    ['id', 'name', 'price', 'amount'],
    ['1', 'apple', '5000', '5'],
    ['2', 'pencil', '500', '42'],
    ['3', 'pineapple', '8000', '5'],
    ['4', 'pen', '1500', '10']
]

csv_file = open('sample12.csv',"w")

writer = csv.writer(csv_file, lineterminator="\n")
writer.writerows(data)

csv_file.close()

In [9]:
# 데이타 분석에서는 판다스로 처리

import pandas as pd

names = ['Kim', 'Park', 'Lee', 'Shin']
ages = [25, 29, 21, 33]
address = ['서울', '대구', '춘천', '제주']

dictionary = {
    'name' : names,
    'age' : ages,
    'address' : address
}

df = pd.DataFrame(dictionary)

df.info()

#인덱스 열 없이 저장
df.to_csv("사원정보.csv",index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     4 non-null      object
 1   age      4 non-null      int64
 2   address  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [12]:
# csv 를 pandas로 읽어 들이기
import pandas as pd

df_emp = pd.read_csv("emp.csv")

df_emp.info()
df_emp.describe()
df_emp.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     14 non-null     int64
 1   ename     14 non-null     object
 2   job       14 non-null     object
 3   mgr       13 non-null     float64
 4   hiredate  14 non-null     object
 5   sal       14 non-null     int64
 6   comm      4 non-null      float64
 7   deptno    14 non-null     int64
dtypes: float64(2), int64(3), object(3)
memory usage: 1.0+ KB

   empno   ename        job     mgr    hiredate   sal    comm  deptno
0   7839    KING  PRESIDENT     NaN  1981-11-17  5000     NaN      10
1   7698   BLAKE    MANAGER  7839.0  1981-05-01  2850     NaN      30
2   7782   CLARK    MANAGER  7839.0  1981-05-09  2450     NaN      10
3   7566   JONES    MANAGER  7839.0  1981-04-01  2975     NaN      20
4   7654  MARTIN   SALESMAN  7698.0  1981-09-10  1250  1400.0      30

In [14]:
%%writefile sample.json

[
    {
      "id": "A001",
      "city": "Tokyo",
      "country": "Japan",
    },
    {
      "id": "B012",
      "city": "Jerusalem",
      "country": "Isreal",
    },
    {
      "id": "C123",
      "city": "Busan",
      "country": "South Korea",
    }
]

Overwriting sample.json

In [15]:
# JSON은 JavaScript Object Notation의 약자로,
# 데이터를 구조화하여 저장하거나 전송할 때 사용하는 포맷
# 주로 웹에서 클라이언트와 서버 간 데이터 교환에 사용

# 가볍고 텍스트 기반이라 사람이 읽고 쓰기 쉬움
# 대부분의 프로그래밍 언어에서 쉽게 읽고 생성 가능
# **키-값 쌍(key-value pair)**으로 구성된 데이터 구조 사용

df_json = pd.read_json("sample.json")


df_json.info()
df_json.describe()
df_json.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3 non-null      object
 1   city     3 non-null      object
 2   country  3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

     id       city      country
0  A001      Tokyo        Japan
1  B012  Jerusalem       Isreal
2  C123      Busan  South Korea

In [17]:
# 웹에서 json 가져오기
url = "https://jsonplaceholder.typicode.com/users"
df_json = pd.read_json(url)

df_json.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [22]:
# 데이타 프레임을 json 으로 변환 및 저장
import pandas as pd

data = {
        '이름': ['John', 'Doe', 'Jane'],
        '나이': [30, 25, 28],
        '성별': ['남성', '남성', '여성']
        }

df = pd.DataFrame(data)

print(df.head())

#데이타프레임을 json 으로 바꿈
json_data = df.to_json(orient="records",indent=4)
print(json_data)

# 데이타 프레임을 JSON 파일로 바로 저장
# 각 행을 JSON 객체로 변환 (리스트 형태)
df.to_json('행기준.json', orient="records",force_ascii=False,indent=4)
df.to_json('열기준.json', orient="columns",force_ascii=False,indent=4)

     이름  나이  성별
0  John  30  남성
1   Doe  25  남성
2  Jane  28  여성
[
    {
        "\uc774\ub984":"John",
        "\ub098\uc774":30,
        "\uc131\ubcc4":"\ub0a8\uc131"
    },
    {
        "\uc774\ub984":"Doe",
        "\ub098\uc774":25,
        "\uc131\ubcc4":"\ub0a8\uc131"
    },
    {
        "\uc774\ub984":"Jane",
        "\ub098\uc774":28,
        "\uc131\ubcc4":"\uc5ec\uc131"
    }
]

In [31]:
%%writefile test.xml
<?xml version="1.0" encoding="utf-8"?>
<world name = "주소록과 네이버 API 서비스키">    
    <people name='김민국' >
        <age>15</age>
        <tall>183cm</tall>
        <add>서울시 서대문구</add>
    </people>    
    <people name='박한솔' >
        <age>30</age>
        <tall>175cm</tall>
        <add>서울시 용산구</add>
    </people>    
    <naver_api>
        <client_id>JXRlq56Db1L0PA</client_id>
        <client_secret>hwiniqqkgvH</client_secret>
    </naver_api>    
</world>

Overwriting test.xml

In [ ]:
import xml.etree.ElementTree as ET

tree = ET.parse("test.xml")
root = tree.getroot()
print(root.tag)
print(root.get('name'))

for child in root:
    print(child.tag, child.attrib)

for age in root.iter("age"):
    print(age.text)

for addr in root.iter("add"):
    print(addr.text)

# world 안에 있는 사람들의 키의 합은?

tall_sum = 0
for tall in root.iter("tall"):
    print(tall.text)
    tall_sum = tall_sum + int(tall.text.replace("cm","")) # "183cm" -> 183
 
print("키의 합:", tall_sum)

world
주소록과 네이버 API 서비스키
people {'name': '김민국'}
people {'name': '박한솔'}
naver_api {}
15
30
서울시 서대문구
서울시 용산구
183cm
175cm
키의 합: 358

In [40]:
# 엑셀 파일 다루기
# DataFrame -> 엑셀로 저장

import pandas as pd

data = {
    "이름": ["홍길동", "김영희", "이철수"],
    "나이": [30, 25, 28],
    "직업": ["개발자", "디자이너", "기획자"]
}

df = pd.DataFrame(data)

# 엑셀 파일로 저장
df.to_excel("데이터.xlsx",index=False)

# 엑셀 파일 읽기
df_excel = pd.read_excel("데이터.xlsx")

df_excel.info()
df_excel.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      object
 1   나이      3 non-null      int64
 2   직업      3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

    이름  나이    직업
0  홍길동  30   개발자
1  김영희  25  디자이너
2  이철수  28   기획자

In [ ]:
# 웹 크롤링 할때 자주 사용 되는 Python 라이브러리 BeautifulSoup과 Selenium
# BeautifulSoup 라이브러리를 이용하여 xml파일을 아래와 같이 파싱하여 텍스트 데이터를 추출

#pip install beautifulsoup4
from bs4 import BeautifulSoup

# f = open("test.xml","r")
# f.close()

with open("test.xml","r",encoding="utf-8") as f:
    xml_doc = f.read()

soup = BeautifulSoup(xml_doc,"xml")

for people in soup.find_all("people"):
    print(people.get('name'))
    print(people.age.text)
    print(people.tall.text)
    print(people.add.text)
    

# naver_api의 id 와 key 를 출력하시오.
for naver_api in soup.find_all("naver_api"):
    print(naver_api.client_id.text)
    print(naver_api.client_secret.text)

김민국
15
183cm
서울시 서대문구
박한솔
30
175cm
서울시 용산구
JXRlq56Db1L0PA
hwiniqqkgvH

In [ ]:
# 지식인에 검색어를 넣으면, 가장 위에 나오는 검색결과

#pip install beautifulsoup4
from bs4 import BeautifulSoup

# requests 는 크롬(또는 엣지)과 같은 웹브라우져 라고 생각 하면 됨
import requests 

search = input("검색어를 넣으시오")

#url = "https://kin.naver.com/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC"

url = "https://kin.naver.com/search/list.naver?query=" + search


response = requests.get(url)
#print(response.text)

html = response.text

#document.querySelector("#s_content > div.section > ul > li:nth-child(1) > dl > dt > a")

soup = BeautifulSoup(html, "html.parser")
#<a href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=10402&amp;docId=486888460&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank" class="_nclicks:kin.txt _searchListTitleAnchor"><b>파이썬</b> random 함수 질문</a>
title = soup.select_one('#s_content > div.section > ul > li:nth-child(1) > dl > dt > a')
print(title)
print(title.get_text())

<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=6&amp;dirId=60204&amp;docId=487118125&amp;qb=7Zy064yA7Y+w&amp;enc=utf8" target="_blank">이혼소송중<b>휴대폰</b>통화기록을딸수있을까요?</a>
이혼소송중휴대폰통화기록을딸수있을까요?